import { useNavigate } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'

export default function TermsPage() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen px-5 pb-16" style={{ background: '#0F1117' }}>
      {/* Header */}
      <div className="flex items-center gap-3 pt-10 pb-6">
        <button
          onClick={() => navigate(-1)}
          className="p-2 rounded-xl"
          style={{ background: '#1A1D2E', color: '#8B8BA7' }}
          aria-label="Go back"
        >
          <ArrowLeft size={18} />
        </button>
        <h1 className="text-xl font-bold" style={{ color: '#E8E8F0' }}>Terms of Service</h1>
      </div>

      <div className="flex flex-col gap-6 max-w-2xl" style={{ color: '#8B8BA7' }}>
        <p className="text-xs" style={{ color: '#6C63FF' }}>Last updated: March 2025</p>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold" style={{ color: '#E8E8F0' }}>About MindShift</h2>
          <p className="text-sm leading-relaxed">
            MindShift is an ADHD-aware productivity app. It is not a medical device and does not
            provide medical advice, diagnosis, or treatment. Use it as a supportive tool alongside
            professional support where relevant.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold" style={{ color: '#E8E8F0' }}>Your account</h2>
          <p className="text-sm leading-relaxed">
            You are responsible for maintaining the security of your account. Use a strong, unique
            email address. We use magic-link authentication (no password stored). Notify us
            immediately if you suspect unauthorized access.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold" style={{ color: '#E8E8F0' }}>Acceptable use</h2>
          <p className="text-sm leading-relaxed">
            You agree not to use MindShift to generate or store harmful, illegal, or abusive
            content. You agree not to reverse-engineer, scrape, or abuse the AI features. We
            reserve the right to suspend accounts that violate these terms.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold" style={{ color: '#E8E8F0' }}>AI features</h2>
          <p className="text-sm leading-relaxed">
            AI-generated task breakdowns and recovery messages are suggestions only. They may
            occasionally be inaccurate or imperfect. Always use your own judgment. AI responses
            are generated by third-party models (Anthropic Claude) and are subject to their terms.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold" style={{ color: '#E8E8F0' }}>Limitation of liability</h2>
          <p className="text-sm leading-relaxed">
            MindShift is provided "as is" without warranty. We are not liable for any indirect,
            incidental, or consequential damages arising from your use of the app, including any
            productivity outcomes or data loss.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold" style={{ color: '#E8E8F0' }}>Changes to these terms</h2>
          <p className="text-sm leading-relaxed">
            We may update these terms occasionally. Continued use of MindShift after changes
            constitutes acceptance. We'll notify you of significant changes via email.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold" style={{ color: '#E8E8F0' }}>Contact</h2>
          <p className="text-sm leading-relaxed">
            Questions about these terms?{' '}
            <a
              href="mailto:hello@mindshift.app"
              style={{ color: '#6C63FF' }}
            >
              hello@mindshift.app
            </a>
          </p>
        </section>
      </div>
    </div>
  )
}
